[package]
name = "RayMarcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
image = "0.24.4"
ndarray = "0.15.4"
rand = "0.8.4"
rayon = "1.5.3"
num = "0.4.1"